name: IRM Autonomy CI

on:
  push:
    branches: [ master, alvin/ci ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: create build
      run: mkdir build && cd build
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: make
      run: make
