name: iRM Autonomy CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # build on ubuntu
  build-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: cache pip
      id: cache-pip
      uses: actions/cache@v2
      with:
        path: ~/.pip
        key: ${{ runner.os }}-pip
    - name: pip
      run: |
        sudo -H pip3 install pip setuptools --upgrade --cache-dir=~/.pip # use latest pip
        sudo -H pip3 install -r requirements.txt --use-feature=2020-resolver --cache-dir=~/.pip
    - name: create build
      run: mkdir build
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Debug ..
      working-directory: build
    - name: build
      run: make -j
      working-directory: build
    - name: MacOS - turn off firewall
      if: matrix.os == 'macos-latest'
      run: |
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw -k
    - name: test
      run: make test
      working-directory: build
