name: IRM Autonomy CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # build on ubuntu
  build-test-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: create build
      run: mkdir build
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Debug ..
      working-directory: build
    - name: build
      run: make
      working-directory: build
    - name: test
      run: make test
      working-directory: build
