name: iRM Autonomy CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # build on ubuntu
  build-test-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: create build
      run: mkdir build
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Debug ..
      working-directory: build
    - name: build
      run: make
      working-directory: build
    - name: test
      run: make test
      working-directory: build
  # build on macos
  build-test-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: create build
      run: mkdir build
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Debug ..
      working-directory: build
    - name: build
      run: make
      working-directory: build
    - name: turn off firewall
      run: |
        sudo defaults write /Library/Preferences/com.apple.alf globalstate -int 0
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw -k
    - name: test
      run: ./utils/tests/lcm_utils_test
      working-directory: build
